language: go
go:
  - 1.4
  - tip
sudo: required
install:
  - sudo apt-get install libXxf86vm-dev libcsfml-dev
  - go get -u github.com/thinkofdeath/gl/v3.2-core/gl
  - go get -u github.com/go-gl/mathgl/...
  - go get -u github.com/go-gl/glfw/v3.1/glfw
